### ISSUE TITLE
请问遇到这个报错怎么解决

### ISSUE THREAD

**Issue by JIANG54864** [gagayuan/runoob-PDF-#8]
Error in transfer html to pdf
'sh' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by JIANG54864** [comment]
补充：
Traceback (most recent call last):
  File "G:\science\program\python\main.py", line 78, in merge_pdf_core
    next_pdf_file = PdfFileReader(open(f, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './pdfs/HTML_教程.pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\science\program\python\main.py", line 163, in <module>
    main()
  File "G:\science\program\python\main.py", line 153, in main
    get_and_merge(dic_total[fold][link],link)
  File "G:\science\program\python\main.py", line 116, in get_and_merge
    merge_pdfs(DIC,chapter_name)
  File "G:\science\program\python\main.py", line 61, in merge_pdfs
    merge_pdf_core(chapter_name,filenames)
  File "G:\science\program\python\main.py", line 83, in merge_pdf_core
    print >>sys.stderr, "%s could not be found." % f
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
